name: Build
on: [workflow_dispatch]
jobs:
  buildArm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7-a, armv8-a] # libsodium don't support x86 static, cry about it
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install make -y
          sudo apt install automake -y
          sudo apt install autoconf -y
          sudo apt install libtool -y
          sudo apt install clang -y
          sudo apt install build-essential -y
          sudo apt install gcc-multilib -y
          git clone https://github.com/jedisct1/libsodium
          sudo chmod -R 777 *
          cd libsodium
          ./autogen.sh -s
          cp -f dist-build/android-armv7-a.sh android-armv7-a.sh
          cp -f dist-build/android-armv8-a.sh android-armv8-a.sh
          cp -f dist-build/android-build.sh android-build.sh
      - name: Build
        run: |
          cd libsodium
          ./android-${{matrix.arch}}.sh LIBSODIUM_FULL_BUILD=yes
      - uses: actions/upload-artifact@v2
        if: matrix.arch == 'armv8-a'
        with:
          name: libsodium-${{matrix.arch}}
          path: libsodium/libsodium-android-${{matrix.arch}}+crypto/lib/libsodium.a

      - uses: actions/upload-artifact@v2
        if: matrix.arch == 'armv7-a'
        with:
          name: libsodium-${{matrix.arch}}
          path: libsodium/libsodium-android-${{matrix.arch}}/lib/libsodium.a

