name: Build
on: [workflow_dispatch]
jobs:
  buildArm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7-a, armv8-a] # libsodium don't support x86 static, cry about it
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install make -y
          sudo apt install automake -y
          sudo apt install autoconf -y
          sudo apt install libtool -y
          sudo apt install clang -y
          sudo apt install build-essential -y
          sudo apt install gcc-multilib -y
          git clone https://github.com/jedisct1/libsodium
          sudo chmod -R 777 *
      - name: Build
        run: |
          cd libsodium
          ./autogen.sh
          cd dist-build
          ./android-${matrix.arch}.sh LIBSODIUM_FULL_BUILD=yes
          tree libsodium/src
      - uses: actions/upload-artifact@v2
        with:
          name: libsodium-${matrix.arch}
          path: libsodium/src/libsodium.a